name: 'python action'

on:
  workflow_dispatch:
  schedule:
    - cron:  '20 22 * * *'
  

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Set up Python 3.7'
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install DingtalkChatbot
      - name: 'sendDingding'
        env:
            WEBHOOK: ${{ Secrets.WEBHOOK }}
            SECERT: ${{ Secrets.SECERT }}
            

        run: python Dingtalk.py


